### ISSUE TITLE
零基础学习kubernetes(四): 利用闲置主机搭建并暴露本地k8s集群 | Leosocy's Blog

### ISSUE THREAD

**Issue by leosocy** [Leosocy/leosocy.github.io#3]
https://blog.leosocy.top/%E9%9B%B6%E5%9F%BA%E7%A1%80%E5%AD%A6%E4%B9%A0kubernetes-%E5%9B%9B-%E5%88%A9%E7%94%A8%E9%97%B2%E7%BD%AE%E4%B8%BB%E6%9C%BA%E6%90%AD%E5%BB%BA%E5%B9%B6%E6%9A%B4%E9%9C%B2%E6%9C%AC%E5%9C%B0k8s%E9%9B%86%E7%BE%A4/ 

 前三章的学习，笔者经历了从使用ECS的k8s集群到本地的Minikube，说白了，还是穷，买不起高配置的ECS，而当资源(cpu/memory)不足时，要想充分发挥k8s的强大功能可以说是难上加难。 恰巧笔者有一台尘封已久的笔记本，很早之前折腾过一阵archlinux系统，如果我们能用它在内网搭建一个k8s集群，然后通过某种方式暴露在公网上供使用，是不是就很nice了呢？ 如果你也有类似的烦恼，想

**Comment by Leosocy** [comment]
test comment by gitalk.

**Comment by leosocy** [comment]
```python
def main():
  print("test")
```
